---
version: "3.8"
services:

  app:
    build:
      context: ./
      target:  php-fpm
    restart:   on-failure
    ports:
      - 9000:9000
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck

  nginx:
    image:     nginx:1.21-alpine
    depends_on:
      - app
    volumes:
      - ./app:/app:ro
      - ./docker/nginx/conf/app.docker-compose.conf:/etc/nginx/conf.d/default.conf:ro
    restart:   on-failure
    ports:
      - 8080:80
